# Simpleng config para hindi malito si Railway
[variables]
    PYTHON_VERSION = "3.11"

[phases.install]
    cmds = ["pip install -r requirements.txt"]

[start]
    # Siguraduhin na tama ang path ng app mo dito
    cmd = "gunicorn -b 0.0.0.0:${PORT:-5000} piyukonek.app:app"
